### ISSUE TITLE
Error In Install

### ISSUE THREAD

**Issue by AhrimanSefid** [TOAD-Joey/TOAD-DA-Sync-Backup#2]
Hi All.
Your connection has timed out
Either your request was invalid or the program hasn't completed your request.
Please notify the server admin

**Comment by boring-joey** [comment]
Hi Ahriman, thank you for contacting us. Sounds like you are trying to connect to a rsync server without the right configuration. Did you add the public ssh key to your remote location? [Check this page for further information.](https://github.com/TOAD-Joey/TOAD-DA-Sync-Backup/wiki/Configure-remote-location) 

If you did, please give us a little bit more information about your setup so we can help you.
