### ISSUE TITLE
Support for Amazon

### ISSUE THREAD

**Issue by filipziger** [TOAD-Joey/TOAD-DA-Sync-Backup#3]
Hi there, I have question/request for you ;)

Are you able to modify the plugin to work with Amazon storage service? If you are able to do that I'm willing to test your service.

**Comment by boring-joey** [comment]
Hi @filipziger, the plugin will work with any storage servers that supports rsync and connection over SSH. If the Amazon storage service supports rsync the plugin can connect to it over SSH.

**Comment by boring-joey** [comment]
@filipziger, just curious if you tried the plugin with the Amazon services?
